-- Migration 011: pricing module tables

CREATE TABLE IF NOT EXISTS pricing_loads (
  id                   VARCHAR(36)  NOT NULL PRIMARY KEY,
  load_number          VARCHAR(50)  NOT NULL UNIQUE,
  client_id            VARCHAR(36)  NULL,
  client_name          VARCHAR(200) NULL,
  sales_person         VARCHAR(200) NULL,
  related_quotation_id VARCHAR(50)  NULL,
  related_booking_id   VARCHAR(50)  NULL,
  transport_mode       ENUM('FCL','LCL','FTL','LTL','AIR','PARCEL','RAIL','BULK','SPECIAL') NOT NULL DEFAULT 'FCL',
  origin               VARCHAR(200) NULL,
  destination          VARCHAR(200) NULL,
  equipment_type       VARCHAR(100) NULL,
  quantity             INT          NULL DEFAULT 1,
  volume_cbm           DECIMAL(12,4) NULL,
  weight_kg            DECIMAL(12,2) NULL,
  cargo_nature         VARCHAR(200) NULL,
  hazardous            TINYINT(1)   NOT NULL DEFAULT 0,
  incoterm             VARCHAR(20)  NULL,
  required_date        DATE         NULL,
  status               ENUM('Open','Quoting','Offers Received','Rate Selected','Closed') NOT NULL DEFAULT 'Open',
  posted_date          DATE         NULL,
  closed_date          DATE         NULL,
  selected_quote_id    VARCHAR(36)  NULL,
  sales_notes          TEXT         NULL,
  pricing_notes        TEXT         NULL,
  created_by           VARCHAR(100) NULL,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pricing_quotes (
  id                       VARCHAR(36)  NOT NULL PRIMARY KEY,
  load_id                  VARCHAR(36)  NOT NULL,
  supplier_id              VARCHAR(36)  NULL,
  supplier_name            VARCHAR(200) NULL,
  carrier_name             VARCHAR(200) NULL,
  transport_mode           VARCHAR(20)  NULL,
  offered_rate             DECIMAL(15,2) NULL,
  currency                 VARCHAR(10)  NOT NULL DEFAULT 'USD',
  base_rate                DECIMAL(15,2) NULL,
  total_rate               DECIMAL(15,2) NULL,
  transit_days             INT          NULL,
  validity_date            DATE         NULL,
  equipment_available_date DATE         NULL,
  remarks                  TEXT         NULL,
  status                   ENUM('Received','Accepted','Declined','Expired') NOT NULL DEFAULT 'Received',
  decline_reason           TEXT         NULL,
  received_date            DATE         NULL,
  responded_date           DATE         NULL,
  responded_by             VARCHAR(100) NULL,
  created_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pq_load FOREIGN KEY (load_id) REFERENCES pricing_loads(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pricing_contracts (
  id               VARCHAR(36)  NOT NULL PRIMARY KEY,
  contract_number  VARCHAR(50)  NOT NULL UNIQUE,
  supplier_id      VARCHAR(36)  NULL,
  supplier_name    VARCHAR(200) NULL,
  transport_mode   ENUM('FCL','LCL','FTL','LTL','AIR','PARCEL','RAIL','BULK','SPECIAL') NOT NULL DEFAULT 'FCL',
  origin           VARCHAR(200) NULL,
  destination      VARCHAR(200) NULL,
  equipment_type   VARCHAR(100) NULL,
  service_level    VARCHAR(50)  NULL,
  base_rate        DECIMAL(15,2) NULL,
  currency         VARCHAR(10)  NOT NULL DEFAULT 'USD',
  total_rate       DECIMAL(15,2) NULL,
  valid_from       DATE         NULL,
  valid_to         DATE         NULL,
  transit_days     INT          NULL,
  frequency        VARCHAR(50)  NULL,
  notes            TEXT         NULL,
  is_active        TINYINT(1)   NOT NULL DEFAULT 1,
  created_by       VARCHAR(100) NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pricing_models (
  id                    VARCHAR(36)  NOT NULL PRIMARY KEY,
  model_name            VARCHAR(200) NOT NULL,
  transport_mode        ENUM('FCL','LCL','FTL','LTL','AIR','PARCEL','RAIL','BULK','SPECIAL') NOT NULL DEFAULT 'FCL',
  calculation_type      ENUM('per_unit','per_weight','per_volume','whichever_greater','custom') NOT NULL DEFAULT 'per_unit',
  base_unit             VARCHAR(50)  NULL,
  description           TEXT         NULL,
  minimum_charge        DECIMAL(15,2) NULL,
  default_validity_days INT          NOT NULL DEFAULT 30,
  rounding_rule         VARCHAR(20)  NULL,
  is_active             TINYINT(1)   NOT NULL DEFAULT 1,
  created_by            VARCHAR(100) NULL,
  created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
